import {sql} from 'bun';

const result = await sql.begin(async tx => {
    await tx`
        CREATE TABLE IF NOT EXISTS recovery_password_codes(
            "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "user_id" INTEGER,
            "recovery_code" INTEGER,
            "used" BOOLEAN,
            "expiration_date" TIMESTAMP DEFAULT NOW() INTERVAL + '10 minutes',
            "created_at" TIMESTAMP DEFAULT NOW()
        )
    `;

    await tx`
        CREATE INDEX recovery_password_code ON recovery_password_codes(user_id, used, expiration_date)
    `
})