import {sql} from 'bun';

const result = await sql.begin(async tx => {
    return [
        await tx`
            CREATE TABLE "users" (
                "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "email" varchar UNIQUE NOT NULL,
                "password" varchar NOT NULL,
                "name" varchar NOT NULL,
                "last_name" varchar NOT NULL,
                "phone" varchar,
                "user_status" char DEFAULT 'A',
                "document_id" varchar UNIQUE NOT NULL,
                "address" varchar NOT NULL,
                "created_at" timestamp DEFAULT (now()),
                "updated_at" timestamp DEFAULT (now())
            )
        `,
        await tx`
            CREATE TABLE "general_status" (
                "id" integer PRIMARY KEY,
                "index" char UNIQUE,
                "value" varchar
            )
        `,
        
        await tx`
            CREATE TABLE "vehicle_status" (
                "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "index" char UNIQUE,
                "value" varchar
            )
        `,

        await tx`
            CREATE TABLE "shipment_status" (
                "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "index" char UNIQUE,
                "value" varchar
            )
        `,

        await tx`
            CREATE TABLE "packaging_type" (
                "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "index" char UNIQUE,
                "value" varchar
            )
        `,

        await tx`
            CREATE TABLE "boolean_status" (
                "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "index" char UNIQUE,
                "value" varchar
            )
        `,

        await tx`
            CREATE TABLE "admin" (
                "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "email" varchar UNIQUE NOT NULL,
                "password" varchar NOT NULL,
                "name" varchar NOT NULL,
                "last_name" varchar NOT NULL,
                "phone" varchar,
                "admin_status" char DEFAULT 'A',
                "document_id" varchar UNIQUE NOT NULL,
                "address" varchar NOT NULL,
                "modified_by" integer,
                "created_at" timestamp DEFAULT (now()),
                "updated_at" timestamp DEFAULT (now())
            )
        `,

        await tx`
            CREATE TABLE "vehicles" (
                "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "model" integer,
                "brand" varchar,
                "type" char NOT NULL,
                "modified_by" integer,
                "license_plate" varchar UNIQUE NOT NULL,
                "vehicle_status" char DEFAULT 'A',
                "created_at" timestamp DEFAULT (now()),
                "updated_at" timestamp DEFAULT (now())
            )
        `,

        await tx`
            CREATE TABLE "couriers" (
                "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "name" varchar NOT NULL,
                "last_name" varchar NOT NULL,
                "phone" varchar,
                "email" varchar NOT NULL,
                "password" varchar NOT NULL,
                "available" char,
                "vehicle_id" integer,
                "courier_status" char DEFAULT 'A',
                "created_at" timestamp DEFAULT (now()),
                "updated_at" timestamp DEFAULT (now())
            )
        `,

        await tx`
            CREATE TABLE "vehicle_routes" (
                "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "vehicle_id" integer,
                "vehicle_weight" decimal(5,2),
                "origin_place" varchar NOT NULL,
                "destination_place" varchar NOT NULL,
                "departure_time" timestamp,
                "arrival_time" timestamp,
                "admin_id" integer,
                "courier_id" integer,
                "created_at" timestamp DEFAULT (now()),
                "updated_at" timestamp DEFAULT (now())
            )
        `,

        await tx`
            CREATE TABLE "shipments" (
                "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "user_id" integer,
                "destination_address" varchar,
                "origin_addres" varchar,
                "shipment_status" char DEFAULT 'A',
                "packaging_type" char,
                "track_id" varchar UNIQUE,
                "vehicle_id" integer NOT NULL,
                "estimated_arrival_time" date,
                "weight" decimal(3,2),
                "created_at" timestamp DEFAULT (now()),
                "updated_at" timestamp DEFAULT (now())
            )
        `,

        await tx`
            ALTER TABLE "admin" ADD CONSTRAINT "admin_modified_by" FOREIGN KEY ("modified_by") REFERENCES "admin" ("id");
            `,
        await tx`
            ALTER TABLE "vehicles" ADD CONSTRAINT "vehicle_modified_by" FOREIGN KEY ("modified_by") REFERENCES "admin" ("id");
        `,

        await tx`
        ALTER TABLE "vehicles" ADD CONSTRAINT "vehicle_status" FOREIGN KEY ("vehicle_status") REFERENCES "vehicle_status" ("index");
        `,
        await tx`
        ALTER TABLE "couriers" ADD CONSTRAINT "courier_status" FOREIGN KEY ("courier_status") REFERENCES "general_status" ("index");
        `,
        await tx`
        ALTER TABLE "shipments" ADD CONSTRAINT "shipment_status" FOREIGN KEY ("shipment_status") REFERENCES "shipment_status" ("index");
        `,

        await tx`
        ALTER TABLE "vehicle_routes" ADD CONSTRAINT "vehicle_routes" FOREIGN KEY ("vehicle_id") REFERENCES "vehicles" ("id");
        `,
        
        await tx`
        ALTER TABLE "couriers" ADD CONSTRAINT "courier_vehicle" FOREIGN KEY ("vehicle_id") REFERENCES "vehicles" ("id");
        `,

        await tx`
        ALTER TABLE "shipments" ADD CONSTRAINT "shipment_packaging_type" FOREIGN KEY ("packaging_type") REFERENCES "packaging_type" ("index");
        `,

        await tx`
        ALTER TABLE "shipments" ADD CONSTRAINT "user_id_shipments" FOREIGN KEY ("user_id") REFERENCES "users" ("id");
        `,

        await tx`
        ALTER TABLE "shipments" ADD CONSTRAINT "shipment_vehicle" FOREIGN KEY ("vehicle_id") REFERENCES "vehicles" ("id");
        `,

        await tx`
        ALTER TABLE "vehicle_routes" ADD CONSTRAINT "admin_vehicle_routes" FOREIGN KEY ("admin_id") REFERENCES "admin" ("id");
        `,
        
        await tx`
        ALTER TABLE "vehicle_routes" ADD CONSTRAINT "courier_vehicle_routes" FOREIGN KEY ("courier_id") REFERENCES "couriers" ("id");
        `,

        await tx`
        ALTER TABLE "couriers" ADD CONSTRAINT "available_courier_status" FOREIGN KEY ("available") REFERENCES "boolean_status" ("index");
        `,
    ];
    
});

console.log(`result ${JSON.stringify(result)}`);